version: '3.1'
services:
  php:
    container_name: selangnangka
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    image: selangnangka:latest
    networks:
        - selangnangka-net
    volumes:
      - ../:/usr/share/app
    environment:
      - ENVIRONMENT=development
  nginx:
    container_name: selangnangka-nginx
    image: nginx
    env_file:
        - ../.env
    restart: always
    networks:
        - selangnangka-net
    links:
        - mariadb-selangnangka
        - mongodb-selangnangka
        - php
    depends_on:
        - mariadb-selangnangka
        - mongodb-selangnangka
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/servers:/etc/nginx/servers
      - ./keys/nginx:/keys
      - ../:/usr/share/app
  mariadb-selangnangka:
    container_name: selangnangka-mariadb
    image: mariadb:10.5
    env_file:
        - ./.env
    restart: always
    networks:
        - selangnangka-net
    ports:
        - "3376:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./etc/mariadb/my.cnf.d:/etc/mysql/conf.d
  mongodb-selangnangka:
    container_name: selangnangka-mongo
    image: bitnami/mongodb:4.2
    env_file:
        - ./.env
    restart: always
    networks:
        - selangnangka-net
    ports:
        - "27018:27017"
    volumes:
        - ./data/mongodb:/data
        - mongo-selangnangka-dev:/bitnami/mongodb
networks:
    selangnangka-net: {}
volumes:
    mongo-selangnangka-dev:
